/**
 * Re-export auth types from @lifeos/types for convenience
 */
export type {
  AuthTokens,
  AuthSession,
  LoginCredentials,
  RegisterCredentials,
  AuthUser,
  RefreshTokenRequest,
  PasswordResetRequest,
  PasswordResetConfirm,
  ChangePasswordRequest,
  EmailVerificationRequest,
  EmailVerificationConfirm,
  PhoneVerificationRequest,
  PhoneVerificationConfirm,
  AuthError,
  JWTPayload,
  JWTRefreshPayload,
  AuthContext,
  UnauthenticatedContext,
  RequestAuthContext,
  LoginResponse,
  RegisterResponse,
  RefreshTokenResponse,
  LogoutResponse,
  PasswordResetResponse,
  EmailVerificationResponse,
  ProfileResponse,
  SessionStorage,
  RefreshTokenStorage,
  PasswordRequirements,
  AuthConfig,
} from '@lifeos/types';